# Generated by Django 2.2 on 2020-06-10 11:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='name',
            field=models.CharField(blank=True, default=False, max_length=200),
        ),
    ]
