# Generated by Django 2.2 on 2020-06-12 11:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0005_auto_20200611_1728'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attendance',
            name='out_time',
            field=models.TimeField(blank=True, default='00:00:00', null=True),
        ),
    ]
