# Generated by Django 2.2 on 2020-06-12 11:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0007_auto_20200612_1722'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attendance',
            name='out_time',
            field=models.TimeField(blank=True, default='17:00:00', null=True),
        ),
    ]
