# Generated by Django 2.2 on 2020-06-12 15:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0010_auto_20200612_2052'),
    ]

    operations = [
        migrations.AddField(
            model_name='attendance',
            name='stats',
            field=models.BooleanField(default=True),
        ),
    ]
