# Generated by Django 2.2 on 2020-06-14 05:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0011_attendance_stats'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attendance',
            name='in_time',
            field=models.TimeField(blank=True, null=True),
        ),
    ]
