# Generated by Django 2.2 on 2020-06-16 11:44

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0016_remove_attendance_month'),
    ]

    operations = [
        migrations.RenameField(
            model_name='leavereportemployee',
            old_name='student_id',
            new_name='emp_id_leave',
        ),
        migrations.AddField(
            model_name='leavereportemployee',
            name='attendance_id_leave',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='attendance.Attendance'),
        ),
        migrations.AlterField(
            model_name='leavereportemployee',
            name='leave_date',
            field=models.DateField(blank=True, default=datetime.date.today, null=True),
        ),
        migrations.AlterField(
            model_name='leavereportemployee',
            name='leave_message',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.DeleteModel(
            name='AttendanceReportMonthly',
        ),
    ]
